### PR TITLE
More consistent language support.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

I am procrastinating on my other projects. 

So I ran through:
- IntelliJ Idea Ultimate
- PHP Storm
- Rider
- CLion
- WebStorm

Looking for things that haven't been colored.  Here's what I found:

## Screens

| Before | After |
| --- | --- |
| Annotation 2020-08-30 135529 |  Annotation 2020-08-30 140645 |
| Annotation 2020-08-30 143354 | Annotation 2020-08-30 143342 |
| Annotation 2020-08-30 143440 | Annotation 2020-08-30 143804 |
| Annotation 2020-08-30 144257 | Annotation 2020-08-30 144127 |
| Annotation 2020-08-30 145120 | Annotation 2020-08-30 145624 |
| Annotation 2020-08-30 152506 | Annotation 2020-08-30 152855 |
| Annotation 2020-08-30 160135 | Annotation 2020-08-30 160354 |

### CODE REVIEW

**Review by mskelton — APPROVED** [review]
Sweet!

**Comment by Unthrottled** [comment]
Just to manage expectations. I've got a couple of thing I want to take care of before I merge this in. I'll probably have some time later this week to get it in. Thanks!

**Comment by Unthrottled** [comment]
Alright, I'm going to target Monday the 7th for this release. 🎉

**Comment by jelinski** [comment]
First of all thanks for this cool theme! I really like it, however there is one issue I'd like to report. 

Built in themes like Darcula visualize commits that are not part of current branch by highlighting them. Unfortunately this feature is not working with "One Dark theme" where all the commits look the same regardless if "Current branch" highlighting is selected or not. Below I post a screenshot.

comparison

Do you know if this is something I can easily tweak on my own? Or maybe there is a chance this will be fixed in next releases of the theme?

Thanks in advance.

**Pull request merged**
