### PR TITLE
2021.2 Build Look and Feel Maintenance

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Some things look a bit off in the 2021.2 Build, this pull request will address all those issues.

# Changes

| Before | After |
| --- | --- |
| Screenshot from 2021-06-05 07-40-02 | Screenshot from 2021-06-05 08-03-05 |
| Screenshot from 2021-06-05 07-43-11 | Screenshot from 2021-06-05 07-51-43 |

# Notes

I checked 2021.1 doesn't have these issues. So I'll leave this PR in draft, and wait until the 2021.2 build is more mature, before releasing this stuffs.

### CODE REVIEW

**Review by mskelton — APPROVED** [review]
Changes look good, so if this continues to be a problem in 2021.2, feel free to merge.

**Comment by Unthrottled** [comment]
Yeah, I was going to wait a bit, just to see if they make more changes that way we aren't annoying users with updates that don't really apply to the IDE that they are currently using.

**Comment by Unthrottled** [comment]
Oh and for clarity, 2021.2 is still in EAP.

**Comment by whyman** [comment]
@Unthrottled you are awesome, thanks for your efforts.

**Comment by Unthrottled** [comment]
@whyman Thank you for the kind words! 

It ain't much, but it's honest work

**Pull request merged**
