### PR TITLE
Release v5.1.1

### LINKED ISSUE #187: Enable distinguishable VCS Current Branch highlighting
First of all thanks for this cool theme! I really like it, however there is one issue I'd like to report. 

Built in themes like Darcula visualize commits that are not part of current branch by highlighting them. Unfortunately this feature is not working with "One Dark theme" where all the commits look the same regardless if "Current branch" highlighting is selected or not. Below I post a screenshot.

comparison

Do you know if this is something I can easily tweak on my own? Or maybe there is a chance this will be fixed in next releases of the theme?

Thanks in advance.

_Originally posted by @jelinski in https://github.com/one-dark/jetbrains-one-dark-theme/pull/184#issuecomment-696333539_

### LINKED ISSUE #190: Plugin not compatible with IntelliJ IDEA 2020.3 EAP
Installing the latest EAP of Intellij IDEA (2020.3) alerts the user that this theme is incompatible.
The exact error is:

Plugin 'One Dark theme' (version '5.1.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.3645.34

IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.3645.34, built on September 22, 2020
IntelliJ IDEA EAP User
Expiration date: October 22, 2020
Runtime version: 11.0.8+10-b1094.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2476M
Cores: 12
Registry: debugger.watches.in.variables=false, ide.images.show.chessboard=true
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains, CheckStyle-IDEA, com.thvardhan.gradianto, net.seesharpsoft.intellij.plugins.csv

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Closes #187 
Closes #190 

# Screenshots

| before | after |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by Unthrottled** [comment]
@jelinski 
For starters, thank you for the kind words! Couldn't have done it without all of the contributors, like you!

I would like to wait to release until we have more substance to the release.

Ideally, this is where we could use [plugin release channels](https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#uploading-a-plugin-update-to-the-custom-release-channel). When I get time later, I'll set up the CI to publish to the `EAP` channel.

However, for the time being, if you want this fix asap. You can download the zip below :point_down: 

[one-dark-theme-5.1.1.zip](https://github.com/one-dark/jetbrains-one-dark-theme/files/5258303/one-dark-theme-5.1.1.zip)

And then [follow these instructions](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) as to how to install from the disk.

**Comment by Unthrottled** [comment]
I'm going to leave this in draft, until I can get the release channels set up.

**Comment by jelinski** [comment]
Wow, that was quick! I'm using the new version and it works like a charm. Thanks a lot :)

**Comment by Unthrottled** [comment]
Change of plan. I included the fix for #190 . Which makes these changes candidate for a release.

So this will be part of the v5.1.1 release. I still want to eventually do the canary release some time in the future.

**Pull request merged**
