### PR TITLE
Add 2023.3 Build Support

### LINKED ISSUE #314: WebStorm 2023.3 EAP support
изображение

### PR DESCRIPTION
**Pull request by simPod**
Add 2023.3 Build Support

#### Description
Add 2023.3 Build Support

#### Motivation and Context
Need 2023.3 Build Support

#### Screenshots (if appropriate):

image

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-Functional Change (non-user facing changes)

#### Checklist:

- [x] My code follows the code style of this project (`./gradlew check` passes clean).
    - Tip: If you have lint issues just run `./gradlew :ktlintMainSourceSetFormat`.
- [x] I updated the changelog with the new functionality.

Resolves #314

_CI pass https://github.com/simPod/jetbrains-one-dark-theme/actions/runs/6390508871/job/17343905896_

### CODE REVIEW

**Comment by simPod** [comment]
For anyone interested here's the build 

[one-dark-theme.zip](https://github.com/one-dark/jetbrains-one-dark-theme/files/12819045/one-dark-theme.zip)

**Comment by Navrin** [comment]
> For anyone interested here's the build
> 
> [one-dark-theme.zip](https://github.com/one-dark/jetbrains-one-dark-theme/files/12819045/one-dark-theme.zip)

Thank you for this, works on my MBP with build 233.9102.97. Aesthetics restored!

**Comment by wyatt-herkamp** [comment]
Works on Rust Rover 2023.3(233.8264.22)

**Comment by surgicalcoder** [comment]
Works on Rider 2023.3 EAP 2 (233.9102.265)

**Comment by Unthrottled** [comment]
Thank you for getting a head on this, much appreciated :)

**Pull request merged**
