### PR TITLE
2021 Build Support

### LINKED ISSUE #203: Title bar font color
With dark theme, the title bar font is too faint to see. Is there a way to set that color?

### LINKED ISSUE #204: 2021.1 EAP Build Support
The new 2021.1 EAP is out, it's time to jump on the release train!

### PR DESCRIPTION
**Pull request by Unthrottled**
# Changes

- Updated Windows 10 Title Pane Foreground (Closes #203 )
- Updated Sentry Client
- Triggering a new build on release will also add 2021.1 build support (Closes #204)

## Screen Shot
| Before | After |
| --- | --- |
| Image | image |

### CODE REVIEW

**Review by mskelton — APPROVED** [review]
Nice

**Comment by whyman** [comment]
Please release this and save me from Darcula :bow:

**Comment by Unthrottled** [comment]
@whyman Salvation is at hand, v5.1.4 is now available for installation. :joy:

**Comment by yxd0018** [comment]
Thanks a lot. I guess the color is fixed, right?

**Comment by Unthrottled** [comment]
@yxd0018 Yeah, you might have to restart the IDE for it to take effect. (The theme probably installed without restart, right?)

Oh yeah, I thought that the color customization was something that would be better as part of another plugin, so it could be used on any theme. If you really want that you could submit an issue to the [themed components](https://github.com/Unthrottled/themed-components) plugin.

**Comment by yxd0018** [comment]
I installed themed component, but it says "feature only works on Mac OS" :(

**Pull request merged**
